### ISSUE TITLE
add semi-colon between files

### ISSUE THREAD

**Issue by pmuellr** [pmuellr/cat-source-map#6]
Currently have a situation where browserify writes the following line:

```
},{"...":"...","...":"tQI123"}]},{},[25])
```

and the next file is a compiled coffeescript without --bare, and so

```
(function() {
  ...
}).call(this);
```

This is bad.  Inserting a semi-colon between the files will fix it.

**Comment by pmuellr** [comment]
You are now a "collaborator" here.  Go ahead and merge the PR - prefer to not see specific "merge" commits, if you can FF-it so the tree stays linear, would prefer it that way.  Not a biggie.

What's your npm userid, I'll do an addowner or whatever there, and then you should be good to go!

**THANK YOU VERY MUCH!  YOU MADE MY FRIDAY!**

**Comment by yannickcr** [comment]
Thanks, I'll try to take care of this early next week.

My npm userid is [yannickcr](https://www.npmjs.com/~yannickcr)

**Comment by pmuellr** [comment]
Added you as an owner at npm, so you should be able to publish a new version:

```
$ npm owner ls cat-source-map
pmuellr <email-address>
yannickcr <email-address>
```

Let me know if you have any questions, and thanks again!
